title: Developer Notebook
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Developer Notebook
baseurl: "/notebook" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Theme specific configs
remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0

# Exclude from processing
exclude:
  - scripts/
  - docker/
  - README.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
