services:
  create-new:
    image: jekyll/jekyll:4.2.2
    container_name: jekyll-new
    environment:
      MY_ENV_VAR_DUMMY: 'service_named_create_new'
    volumes:
      - '../.:/srv/jekyll'
    ports:
      - 4000:4000 # (localhost port) => (docker port)
    command: sh docker/docker-compose-new.sh --new
